[package]
name = "sawatuma_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sawatuma_rs"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.13.0"
pyo3 = "0.20.0"
